// <auto-generated />
namespace PocsKft.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class harmadik : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(harmadik));
        
        string IMigrationMetadata.Id
        {
            get { return "201312012303528_harmadik"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
