// <auto-generated />
namespace PocsKft.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class masodik : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(masodik));
        
        string IMigrationMetadata.Id
        {
            get { return "201312012003450_masodik"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
